### ISSUE TITLE
ASN1_TIME_set_string_X509

### ISSUE THREAD

**Issue by 89z** [dweinstein/rs-google-play#1]
When I compile the tool, I get this if I try to run:

~~~
gpapi-cli.exe - Entry Point Not Found
---------------------------
The procedure entry point ASN1_TIME_set_string_X509 could not be located in the
dynamic link library
C:\rs-google-play-master\target\debug\gpapi-cli.exe. 
~~~

**Comment by dweinstein** [comment]
not sure about this one as I never tried it on windows. Let me know if you figured it out.

**Comment by 89z** [comment]
Yeah, I dont like that this package is relying on a C library, so I just wrote my own using Go:

https://github.com/89z/mech/tree/cbfc2a60/research/play

also you might want to double check if this package even works anymore, as Google is doing TLS fingerprinting now:

https://github.com/89z/mech/blob/cbfc2a60/research/play/hello.go

**Comment by dweinstein** [comment]
@89z recommend using the fork over here https://github.com/EFForg/rs-google-play (it's also now up in cargo)

**Comment by 89z** [comment]
Thanks for the tip :|
